print("\nPROGRAM TRANSLASI")
x1_awal = int(input("Masukkan Nilai x1: "))
y1_awal = int(input("Masukkan Nilai y1: "))
x2_awal = int(input("Masukkan Nilai x2: "))
y2_awal = int(input("Masukkan Nilai y2: "))
x3_awal = int(input("Masukkan Nilai x3: "))
y3_awal = int(input("Masukkan Nilai y3: "))

print("\nPosisi Awal")
print("titik 1: ",x1_awal,",",y1_awal)
print("titik 2: ",x2_awal,",",y2_awal)
print("titik 3: ",x3_awal,",",y3_awal)

tx = int(input("Masukkan Nilai Translasi x: "))
ty = int(input("Masukkan Nilai Translasi y: "))

print("\nPosisi Akhir")
print("titik 1: ",x1_awal+tx,",",y1_awal+ty)
print("titik 2: ",x2_awal+tx,",",y2_awal+ty)
print("titik 3: ",x3_awal+tx,",",y3_awal+ty)